
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinebooker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: cinebooker.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cinebooker
            port:
              number: 80
  tls:
  - hosts:
    - cinebooker.yourdomain.com
    secretName: cinebooker-tls
